### ISSUE TITLE
Make a better use of genind object

### ISSUE THREAD

**Issue by jgx65** [jgx65/hierfstat#1]

**Comment by thibautjombart** [comment]
A note on this, to get relevant data from a *genind* or a *genpop* object, you mostly need only to use `tab(...)`. Examples using *nancycats*:
```r
## load toy data
data(nancycats)
x <- nancycats

## get individual allele counts:
ind.counts <- tab(x)

## get individual allele frequencies
ind.freq <- tab(x, freq=TRUE)

## get allele counts per groups, with a group factor 'grp'
pop(x) <- grp
grp.counts <- tab(genind2genpop(x))

## get allele frequencies per groups, with a group factor 'grp'
pop(x) <- grp
grp.freq <- tab(genind2genpop(x), freq=TRUE)
```
So basically using native genind objects should be relatively straightforward?

**Comment by jgx65** [comment]
Merci Thibault!


Une chose aussi, je t’avais parlé d’un cours genet/genomique  des pops et  R à Lausanne, j’ai obtenu le financement (été 2016), je vous écrit a ce propos des que l’eseb est terminé.

Tt de bon,

Jerome

**Comment by thibautjombart** [comment]
Cool! =D

**Comment by jgx65** [comment]
Function `genind2hierfstat` in `hierfstat` should do most of the trick
