### ISSUE TITLE
varcomp.glob

### ISSUE THREAD

**Issue by VincentDamotte** [jgx65/hierfstat#16]
Hi,
I am working on a dataset of 100,000 individuals / 1000 SNPs and am getting some errors when using the varcomp.glob() function.
I did some tests on 100, 500 and 1,000 individuals and everything ran well. However when running test on 10,000 individuals, i am getting this error (non-french speakers, i am sorry!):

Error in x[, i] <- rep(1:length(dum1), dum1) : 
  le nombre d'objets à remplacer n'est pas multiple de la taille du remplacement
De plus : Warning messages:
1: In dum[[j]]^2/thisdum :
  la taille d'un objet plus long n'est pas multiple de la taille d'un objet plus court
2: In dum[[j]]^2/thisdum :
  la taille d'un objet plus long n'est pas multiple de la taille d'un objet plus court

Do you know what happens?
Thanks
Vincent

**Comment by jgx65** [comment]
Hi,

I'll look into this.  Could you send me a ( if possible brief) example  reproducing the error?  Could you send me the output of `ind.count()`on your object?

Jerome

**Comment by jgx65** [comment]
Any more on this issue? Have you been able to fix it?
