### ISSUE TITLE
write function for estimating weir&cockerham for 2 populations only

### ISSUE THREAD

**Issue by jgx65** [jgx65/hierfstat#2]

**Comment by thierrygosselin** [comment]
Hi Jérôme, how about we work on this with a milestone and integrate this with 2 other enhancement tag?
Cheers 
Thierry

**Comment by jgx65** [comment]
see issue #3 ?

**Comment by jgx65** [comment]
I think tji sissue too was resolved with `fst.dosage`, @thierrygosselin would you agree?

**Comment by thierrygosselin** [comment]
yes all good
