### ISSUE TITLE
Request to update hierfstat to CRAN

### ISSUE THREAD

**Issue by zkamvar** [jgx65/hierfstat#29]
Hi Jerome,

I'm digging up #8 again and requesting for hierfstat to be updated on CRAN as it has several bug fixes from the past three years that would prevent issues like #27. 

Best,
Zhian

**Comment by zkamvar** [comment]
Bumping this because hierfstat on CRAN is as old as children who would be entering kindergarten (were it not for the pandemic).

**Comment by jgx65** [comment]
Just made quite a few updates, checking through them, updating vignettes and will do. might ask for some help regarding testing @zkamvar

**Comment by jgx65** [comment]
Done



> This was generated from CRAN.R-project.org/submit.html]
> 
> The following package was uploaded to CRAN:
> ===========================================
> 
> Package Information:
> Package: hierfstat 
> Version: 0.5-02 
> Title: Estimation and Tests of Hierarchical F-Statistics 
> Author(s): Jerome Goudet [aut, cre], Thibaut Jombart [aut], Zhian N. 
>   Kamvar [ctb], Eric Archer [ctb], Olivier Hardy [ctb] 
>

**Comment by jgx65** [comment]
latest version of hierfstat on [CRAN now :](https://cran.r-project.org/web/packages/hierfstat/index.html)

**Comment by zkamvar** [comment]
Hooray!

![](https://media1.tenor.com/images/dcfb8d8897906f156cf0a4df9c8c8908/tenor.gif)

**Comment by thierrygosselin** [comment]
GitHub actions makes testing so much easier than Travis CI and AppVeyor now...
`??usethis::use_github_actions`

**Comment by jgx65** [comment]
I'll check it, thanks for the tip!
