### ISSUE TITLE
make use of genlight object (adegenet)

### ISSUE THREAD

**Issue by jgx65** [jgx65/hierfstat#3]

**Comment by thierrygosselin** [comment]
For W&C, at least, I've got an option that deals with : vcf, plink, hierfstat/fstat, genepop, genind, genlight, strataG files...
Thierry

**Comment by jgx65** [comment]
I think this is obsolete now, I have created a series of function to deal with allelic dosage that fill this need I believe. @thierrygosselin , let me know if something else is missing?

**Comment by thierrygosselin** [comment]
allelic dosage... all good on my end.

Je vois beaucoup de problème avec les jeux de données génomiques, particulièrement RAD et compagnie, par rapport à l'hétérozygotie individuelle, c'est directement relié au _wet lab_ et stratégies de séquençage, mais au final ce sont les couvertures alléliques qui deviennent biaisés. Du coup les statistiques comme le Fst le sont aussi...

**Comment by jgx65** [comment]
Indeed, but this is a "Garbage in, Garbage out" problem more than one of estimation.  I'll close the issue, thanks for teh feedback!
