### ISSUE TITLE
Error because typo in fstat.from.adegenet.R header

### ISSUE THREAD

**Issue by VitorAguiar** [jgx65/hierfstat#30]
I got the following error when trying to install hierfstat with `devtools::install_github()`:

`Error : (converted from warning) /tmp/RtmpYvI5iE/R.INSTALL1eca1279ea8f/hierfstat/man/fstat.from.adegenet.Rd:23: unexpected section header ‘\details’`

Apparently this is cause by a missing "}" to close the "\dontrun" section. I forked the repo, edited the fstat.from.adegenet.R file to include the missing "}", and the package installs OK.

**Comment by jgx65** [comment]
fixed
