### ISSUE TITLE
I can‘t find the example file（ “examplehier.txt”）

### ISSUE THREAD

**Issue by zxy1555847** [jgx65/hierfstat#38]
hello 
I am learning HierFstat recently to estimate F-statistics of my data
I have noticed that there is a example file in article “A step-by-step tutorial to use HierFstat to analyse populations hierarchically structured at multiple levels”，But the link offered by author shows that the page has been migrated.
so ，anyone can give me a link or file for this?
thank you very much

**Comment by jgx65** [comment]
you can find this file at [http://www.t-de-meeus.fr/examplehier.txt](http://www.t-de-meeus.fr/examplehier.txt)
