### ISSUE TITLE
boot.ppfst

### ISSUE THREAD

**Issue by jwwhale** [jgx65/hierfstat#43]
Hello,

I'm trying to gather CIs on my GBS-like SNP dataset. I'm using a genind object, and am using the following code:  
`data <- read.genepop("data.gen", code =2L)`
`data.CI<- boot.ppfst(data, nboot = 100, quant = c(0.025, 0.975), diploid = T)`

But receiving this error:  Error in i + 1 : non-numeric argument to binary operator

I have also run `data1 <- genind2hierfstat(data)` and still get the same error. My populations are all organised together. 

I can calculate the global Fst on the dataset using the `wc` function, and can get the lsiga, lsigb, and lsigw values from performing `wc(data)$sigma.loc` but not perform the boot.ppfst function.

Any assistance would be hugely grateful.

Cheers,
John

**Comment by jgx65** [comment]
could you send a (small) example reproducing the behavior? Cheers

**Comment by jwwhale** [comment]
Hopefully you mean the following...
`data <- read.genepop("medtest.gen", ncode = 2L)`
 Converting data from a Genepop .gen file to a genind object... 
File description:  Mediana_7773SNPs_12Pops 
...done.
`medtest <- boot.ppfst(data, nboot = 100, quant = c(0.025, 0.975), diploid = TRUE)`
Error in i + 1 : non-numeric argument to binary operator
`wc(data)$sigma.loc`
        SNP                  lsiga                  lsigb              lsigw
M00001  2.566286e-02  3.802011e-03  0.47457627
M00002  6.928440e-02  4.692108e-02 0.34745763
M00003  3.936859e-02  2.079705e-01  0.13131313
...

Then when converting the genind object

`data1 <- genind2hierfstat(data)`
`class(data1)`
[1] "data.frame"
`medtest<- boot.ppfst(data1, nboot = 100, quant = c(0.025, 0.975), diploid = TRUE)`
Error in i + 1 : non-numeric argument to binary operator

**Comment by jgx65** [comment]
Sorry, what I meant was a small dataset reproducing the error you are getting.  I suspect it is due to some loci being missing for whole populations, but would need to see the data to be sure. Cheers

**Comment by jgx65** [comment]
alternatively you can share the data via PM if you can't reproduce the behavior

**Comment by jgx65** [comment]
The issue is in `pp.fst`, I had not caught it: this function expects numbers rather than factors for population identifiers.  A quick and dirty fix is 

`data1<-genind2hierfstat(data)
data1[,1]<-as.integer(data1[,1])
medtest<-boot.ppfst(data1,...)
`

Will fix the function in future versions. 

Hope this helps

**Comment by jwwhale** [comment]
Awesome!! Thanks Jerome!
