### ISSUE TITLE
Cannot install package... 

### ISSUE THREAD

**Issue by dylanHco** [jgx65/hierfstat#45]
Anyone else experiencing this issue? Was the package recently removed? 

Error: Failed to install 'hierfstat' from GitHub:
  (converted from warning) installation of package 'units' had non-zero exit status

Thanks for any suggestions.
-Dylan

**Comment by jgx65** [comment]
from the error message, the problem seems to be coming from the `units` package.   I often find it easier not to update the packages `install_github` asks to update.

**Comment by dylanHco** [comment]
Hi Jerome, 

Thanks for the advice! I have gotten this error many times before, and never realized it was due to the 'units' package... I was able to install hierfstat with install.packages. I think partly my issue,  I am using R with Jupyter notebooks, and it does allow me to respond when it asks which packages I want to install. I think I actually figured out a solution to this as well. I can install the package thru terminal, and just load the library on jupyter. Thanks for your comment!

-Dylan
