### ISSUE TITLE
Inconsistency in genet.dist function

### ISSUE THREAD

**Issue by akamolphat** [jgx65/hierfstat#48]
There are some inconsistencies with the genet.dist function. The result from executing the function with a genind object is not the same as with a dataframe. Please see an example below:

```{r}
library(adegenet)
library(hierfstat)
data("nancycats")
a <- genet.dist(nancycats, method = "WC84")
b <- genet.dist(as.data.frame(cbind(locality = nancycats$pop, nancycats$tab)), diploid = T, method = "WC84")
```

Note that a and b are not the same. I think it has something to do with the genind2hierfstat function which was used in the genet.dist function to automatically convert genind object to a dataframe.

```{r}
nancy <- genind2hierfstat(nancycats)
nancy2 <- as.data.frame(cbind(locality = nancycats$pop, nancycats$tab))

a2 <- genet.dist(nancy, method = "WC84")
b2 <- genet.dist(nancy2, method = "WC84")
```
I understand that the function does not mention using genind object but there are tutorials out there that suggests that genind object can be used (e.g. https://tomjenkins.netlify.app/2020/09/21/r-popgen-getting-started/#5). I thought it would be good to point this out anyways as the function executes with no warnings when a genind object is used.

**Comment by jgx65** [comment]
To convert a genind object to hierfstat format, the `genind2hierfstat` is the one to use.  `nancy2`  is not in the correct `hierfstat` format.  to get the Weir & Cockerham pairwise  Fsts, teh results from a or a2 in your example are correct, not those from b and b2.

**Comment by jgx65** [comment]
Note that you may use the `fs.dosage` function on `nancy2` , and its component `Fst2x2`.  This is not exactly the same as pairwise WC84 (unless sample sizes are identical), but we (Weir and Goudet 2017) recommend using this new estimator when the assumption of independence of populations cannot be made (which is mots often the case)

**Comment by akamolphat** [comment]
Hi Jerome,

Thank you :)

Yours sincerely,
Kamolphat Atsawawaranunt
