### ISSUE TITLE
Pass the check

### ISSUE THREAD

**Issue by thibautjombart** [jgx65/hierfstat#5]
I currently get (as of b63d8dccf6a2907b9fa17ae586e1e735fb863b52):
```r
> check()
Updating hierfstat documentation
Loading hierfstat
Writing fstat.from.adegenet.Rd
'/usr/local/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  CMD build '/home/thibaut/dev/hierfstat' --no-resave-data --no-manual 

* checking for file ‘/home/thibaut/dev/hierfstat/DESCRIPTION’ ... OK
* preparing ‘hierfstat’:
* checking DESCRIPTION meta-information ... OK
* excluding invalid files
Subdirectory 'R' contains invalid file names:
  ‘FSTAT.INI’ ‘beta.R.old’ ‘gtrunchier.dat’ ‘gtrunchier.out’ ‘test.dat’
  ‘test.out’
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘hierfstat_0.04-15.tar.gz’

'/usr/local/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  CMD check '/tmp/RtmpTrpAoZ/hierfstat_0.04-15.tar.gz' --timings 

* using log directory ‘/tmp/RtmpTrpAoZ/hierfstat.Rcheck’
* using R Under development (unstable) (2015-04-13 r68171)
* using platform: x86_64-unknown-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘hierfstat/DESCRIPTION’ ... OK
* this is package ‘hierfstat’ version ‘0.04-15’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘hierfstat’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... NOTE
Malformed Description field: should contain one or more complete sentences.
* checking top-level files ... NOTE
File
  LICENSE
is not mentioned in the DESCRIPTION file.
Non-standard file/directory found at top level:
  ‘hierfstat.Rproj’
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... WARNING
Codoc mismatches from documentation object 'wc':
wc
  Code: function(ndat, diploid = TRUE, pol = 0)
  Docs: function(ndat, diploid = TRUE, pol = 0, trim = FALSE)
  Argument names in docs not in code:
    trim

* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking sizes of PDF files under ‘inst/doc’ ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking examples ... ERROR
Running examples in ‘hierfstat-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: betai
> ### Title: Estimation of beta per population
> ### Aliases: betai
> ### Keywords: univar
> 
> ### ** Examples
> 
> dat<-sim.genot(size=100,N=c(100,1000,10000),nbloc=50,nbal=10)
> betai(dat)$betai 
Error: could not find function "betai"
Execution halted
* checking PDF version of manual ... OK
* DONE

Status: 1 ERROR, 1 WARNING, 2 NOTEs
See
  ‘/tmp/RtmpTrpAoZ/hierfstat.Rcheck/00check.log’
for details.
Error: Command failed (1)
In addition: Warning message:
NAMESPACE not generated by roxygen2. Skipped. 
> 

```

**Comment by jgx65** [comment]
Should be all fixed now:
> check()
Updating hierfstat documentation
Loading hierfstat
Writing betas.Rd
Writing fstat.from.adegenet.Rd
Writing gstat.randtest.Rd
Writing sim.genot.t.Rd
Writing write.bayescan.Rd
"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  CMD build "D:\xx\hierfstat" --no-resave-data --no-manual 

* checking for file 'D:\xx\hierfstat/DESCRIPTION' ... OK
* preparing 'hierfstat':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* looking to see if a 'data/datalist' file should be added
* building 'hierfstat_0.04-15.tar.gz'

"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  CMD check "d:\temp\RtmpwtPDLQ/hierfstat_0.04-15.tar.gz" --timings 

* using log directory 'd:/temp/RtmpwtPDLQ/hierfstat.Rcheck'
* using R version 3.2.1 (2015-06-18)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'hierfstat/DESCRIPTION' ... OK
* this is package 'hierfstat' version '0.04-15'
* checking package namespace information ... OK
* checking package dependencies ...Warning: unable to access index for repository https://stat.ethz.ch/CRAN/src/contrib
 OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'hierfstat' can be installed ... [10s] OK
* checking installed package size ... OK
* checking package directory ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... NOTE
prepare_Rd: gstat.randtest.Rd:80-85: Dropping empty section \seealso
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ... [20s] OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... WARNING
Package vignette without corresponding PDF/HTML:
   'hierfstat.Rmd'

* checking running R code from vignettes ...
   'hierfstat.Rmd' using 'UTF-8' ... OK
 OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 WARNING, 1 NOTE

**Comment by jgx65** [comment]
fixed and closed, thanks Thibault
