### ISSUE TITLE
Parallelizing genet.dist() ?

### ISSUE THREAD

**Issue by alexkrohn** [jgx65/hierfstat#53]
Hi there! I'm loving `hierfstat` and am using it quite often. While most of the functions work quite quickly, computing time for `genet.dist()` increases non-linearly with number of populations and SNPs. I was wondering if there was any way to parallelize the calculations to take advantage of multi-core machines, or other ways one might speed up the calculations?

Thanks for your help!

**Comment by jgx65** [comment]
With many markers (>1000), classical `hierfstat` functions will be very slow. Consider using dosage related functions (have a look at the vignettes)

**Comment by alexkrohn** [comment]
Thanks! Will do.
