### ISSUE TITLE
plot boot.ppfst

### ISSUE THREAD

**Issue by andreiaamaral** [jgx65/hierfstat#55]
Hello,

is there a function to plot a heatmap with the matrix obtained using boot.ppfst?
thanks.

**Comment by jgx65** [comment]
Hi Andreia, something like this? 
```

plot.boot.ppfst<-function(x,...){
  a<-dim(x$ll)[1]
  ci<-matrix(nrow=a,ncol=a)
  dimnames(ci)<-dimnames(x$ll)
  for (i in 2:a)
    for (j in 1:(a-1)){
      ci[j,i]<-x$ul[j,i]
      ci[i,j]<-x$ll[j,i]
    }
	image(1:a,1:a,ci,xlab="population",ylab="Population")
}

##example use:

data(gtrunchier)
plot(boot.ppfst(gtrunchier[,-2]))

```

**Comment by courtiol** [comment]
Indirectly, hierfstat depends both on lattice (via ade4) and ggplot2 (via adegenet):
![image](https://user-images.githubusercontent.com/7499666/156020147-70a7ac62-e523-4292-9a0f-0a201bfc29e8.png)
So there would also be the option of declaring a direct dependence to e.g. lattice and coding something with a scale as well.
Such as:
```r
plot.boot.ppfst<-function(x,...){
  a<-dim(x$ll)[1]
  ci<-matrix(nrow=a,ncol=a)
  dimnames(ci)<-dimnames(x$ll)
  for (i in 2:a)
    for (j in 1:(a-1)){
      ci[j,i]<-x$ul[j,i]
      ci[i,j]<-x$ll[j,i]
    }
  lattice::levelplot(ci,xlab="population", ylab="Population", colorkey=list(title="Fst"), ...)
}

data(gtrunchier)
plot(boot.ppfst(gtrunchier[,-2]), col.regions = \(n) rev(grey.colors(n)))
```
![image](https://user-images.githubusercontent.com/7499666/156025092-ceb45c58-e770-4e61-896f-9716a2198dd5.png)

That could open the door for more plotting...

**Comment by jgx65** [comment]
Thanks for the tip! @andreiaamaral , does this solve your question? Cheers
