### ISSUE TITLE
Conversion genind to hierfstat df a little inconsistent

### ISSUE THREAD

**Issue by courtiol** [jgx65/hierfstat#56]
Is there any particular reason why these functions handle a `genind` input:

https://github.com/jgx65/hierfstat/blob/5d173d2cff8f91b14717f2356fd776db4f5edbc0/R/ppboot.R#L17-L19
https://github.com/jgx65/hierfstat/blob/5d173d2cff8f91b14717f2356fd776db4f5edbc0/R/ppboot.R#L50-L52
https://github.com/jgx65/hierfstat/blob/5d173d2cff8f91b14717f2356fd776db4f5edbc0/R/ppboot.R#L112-L114

But not these related ones:
https://github.com/jgx65/hierfstat/blob/5d173d2cff8f91b14717f2356fd776db4f5edbc0/R/pairwise.fst.R#L36-L37
https://github.com/jgx65/hierfstat/blob/5d173d2cff8f91b14717f2356fd776db4f5edbc0/R/pairwise.fst.R#L93-L94

If not, I am happy to write a PR to make things a little more homogeneous.

**Comment by jgx65** [comment]
Just pushed a new version of `pop.freq`, `pairwise.neifst` and `pairwise.Wcfst`, should solve the issue, let me know if you find another function missing the conversion
