### ISSUE TITLE
pairwise.WCfst(genind2hierfstat(x)) and genet.dist(x, method = "WC84") do not yield the same result

### ISSUE THREAD

**Issue by DaniEstevezBarcia** [jgx65/hierfstat#57]
Hi, 

I have just realized that these two functions do not give the same result when they both should be providing (according to the descriptions) pairwise estimated of Fst following Weir and Cockerham 1984.

Best regards

**Comment by jgx65** [comment]
I'm puzzled, it does for me? (see below). Could you provide an example?

**Comment by DaniEstevezBarcia** [comment]
do you add the [, -2] to remove the population column?

**Comment by DaniEstevezBarcia** [comment]
Also, in the genet.dist option I used a genind object. When changed to hierfstat it works, but I thought it also did with genind (it does actually provide a result but it is different)

**Comment by jgx65** [comment]
gtuncatula contains 2 populations column (hierarchical design), the [,-2] is just to remove one of them. With nancycats, the following give me TRUE:

`all.equal(mat2vec(pairwise.WCfst(genind2hierfstat(nancycats))),mat2vec(as.matrix(genet.dist(nancycats,method="WC84"))))`

**Comment by jgx65** [comment]
Note that if you update hierfstat with the current version on github, you won't need the extra genind2hierfstat in pairwise.WCfst

**Comment by DaniEstevezBarcia** [comment]
The new version is not on cran yet right?

Thank you for the answers

**Comment by jgx65** [comment]
no, on github

**Comment by DaniEstevezBarcia** [comment]
Ok, the problem was that the version on cran for some reason was doing something odd with the genind (it did not return error though). With the github version it works.
