### ISSUE TITLE
Basic Stats (and Ho/Hs/Fis) Require Population Name to be Numeric With A Single Population

### ISSUE THREAD

**Issue by alexkrohn** [jgx65/hierfstat#65]
I noticed some odd behavior when there is only a single population. `Ho`, `Hs` and, by extension `basic.stats`, throw an error when the population name is a character instead of an integer. This only seems to happen when there is a single population. I can change my code accordingly to replace the population name with a 1 when there is only one population, but I figured I'd bring the issue to your attention.

Example:
```
  set.seed(24)
  df <- data.frame(pop = c(rep("B", 3), rep("C", 3)), 
                   locus1 = sample(c(0,1,2), 6, replace = TRUE), 
                   locus2 = sample(c(0,1,2), 6, replace = TRUE), 
                   locus3 = sample(c(0,1,2), 6, replace = TRUE))
  
  Ho(df) # Works
  
  df1 <- data.frame(pop = c(rep("B", 6)), 
                    locus1 = sample(c(0,1,2), 6, replace = TRUE), 
                    locus2 = sample(c(0,1,2), 6, replace = TRUE), 
                    locus3 = sample(c(0,1,2), 6, replace = TRUE))
  
  Ho(df1) # Gives: Error in data[dim(data)[1], 1] + 1 : non-numeric argument to binary operator
  
  df2 <- data.frame(pop = c(rep(1, 6)), 
                    locus1 = sample(c(0,1,2), 6, replace = TRUE), 
                    locus2 = sample(c(0,1,2), 6, replace = TRUE), 
                    locus3 = sample(c(0,1,2), 6, replace = TRUE))
  
  Ho(df2) # Works
  
  df3 <- data.frame(pop = c(rep(as.character("1"), 6)), 
                    locus1 = sample(c(0,1,2), 6, replace = TRUE), 
                    locus2 = sample(c(0,1,2), 6, replace = TRUE), 
                    locus3 = sample(c(0,1,2), 6, replace = TRUE))
  
  Ho(df3) # Gives: Error in data[dim(data)[1], 1] + 1 : non-numeric argument to binary operator
```

**Comment by jgx65** [comment]
Just pushed a [new version](https://github.com/jgx65/hierfstat/commit/ebb48fe1f2ad600c16cee9958a353a3b71e6e687) of `basic.stats`, problem should be solved, let me know if it works.  Cheers

**Comment by alexkrohn** [comment]
This is close. In the above example, `df2` and `df3` work, but for any dataframes with >1 population (e.g. `df1`), both `basic.stats` and the internal `Ho` and `Hs` fail. The error given is `object dum.pop not found`.  I think an `else{ dum.pop <- FALSE }` might fix this.

**Comment by jgx65** [comment]
should be solved, thanks

**Comment by jaflury** [comment]
Dear Jerome,

I had the same issue with the population name in basic.stats and it was resolved with the updated function, however I get the same error in boot.ppfis (error message "data[dim(data)[1], 1] + 1 : non-numeric argument to binary operator"). Unfortunately I could not figure out what needs to be changed, could you help me there?

Best, Jana
