### ISSUE TITLE
pairwise.WCfst Error - non-conformable arrays

### ISSUE THREAD

**Issue by silknets** [jgx65/hierfstat#66]
Hello all,

I'm having an issue similar to closed post [here](https://github.com/jgx65/hierfstat/issues/22), but the solutions there aren't sufficient to resolve my issue. I'm trying to generate 2x pairwise FST matrices, one with original microsatellite genotype data (A), and another where that same genotype data has been recoded so that no populations share alleles (B).  I've been able to generate the FST matrices for other datasets (original and recoded versions), but for the current dataset, I have only been able to generate the matrix for the original dataset. For some reason, the recoded dataset throws an error no matter what I try! I have use genind, fasta (.dat), and a dataframe (organized like data(gtrunchier)) for inputs, all with the same error:

recode_pair <- pairwise.WCfst(recode)
Error in 2 * nal * p - mho : non-conformable arrays

Any suggestions for how to resolve this error? Help would be much appreciated! I've attached zipped .dat files for both the original and recoded data. 

Sam S. 
[gafa.zip](https://github.com/jgx65/hierfstat/files/11042042/gafa.zip)
[gafa_recode.zip](https://github.com/jgx65/hierfstat/files/11042044/gafa_recode.zip)

**Comment by jgx65** [comment]
Hi Sam,

There is indeed an issue, it has to do with correctly splitting the alleles. You choose an encoding with 3 digits per allele, but none of your alleles are larger than 99.  If you ad 100100 to all genotypes, things work:

```
 d1<-read.fstat("gafa.dat")
d2<-read.fstat("gafa_out.dat")
d3<-d2
d3[,-1]<-d3[,-1]+100100 #the fix
genet.dist(d1,method="WC84") #works
genet.dist(d2,method="WC84") #does not work
genet.dist(d3,method="WC84") #works

```
I'll work on fixing this, thanks for reporting

**Comment by jgx65** [comment]
@silknets ,

The issue should be resolved (see [code](https://github.com/jgx65/hierfstat/commit/c8d5ea935c40b6a9a12efb17de169aba4c2c9a47)) . Let me know if this is the case. Cheers

**Comment by silknets** [comment]
I re-installed the package from your GitHub and I was able to run the
pairwise.WCfst(recode)  script successfully!

Much appreciated,

Sam Silknetter
