### ISSUE TITLE
plotting the kinship matrix and printing it 

### ISSUE THREAD

**Issue by alasousi85** [jgx65/hierfstat#70]
hi 
i have established a kinship matrix using the beta dosage function in the package. how can i create a graph out of it ? and how can i print it to be applied in my study?

**Comment by jgx65** [comment]
The easiest is to use `image(kinship.object)`  with `kinship.object<-beta.dosage(dos)` and `dos` is your dosage matrix. What do you mean by print it?

**Comment by alasousi85** [comment]
thank you ..
  i have managed to transfer the file to a CVS file that's what i meant by print it (export the file)

**Comment by jgx65** [comment]
OK, issue solved it seems, I'm closing it, you can reopen it if necessary,
