### ISSUE TITLE
boot.ppfst

### ISSUE THREAD

**Issue by Erikacj** [jgx65/hierfstat#71]
I can run pairwise.WCfst on my dataset without issue but when I try to run:

boot <- boot.ppfst(data, nboot=100, quant=c(0.025,0.975))

I get the following error:

Error in apply(x, 2, fun2 <- function(x) sum(x > 0)) : 
  dim(X) must have a positive length
In addition: Warning messages:
1: In max(logical(0), na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
2: In max(logical(0), na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
3: In max(logical(0), na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
4: In min(logical(0), na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
5: In max(logical(0), na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
6: In max(logical(0), na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
7: In names(data.al)[-c(1:2)] <- names(data)[-1] :
  number of items to replace is not a multiple of replacement length

This is what my dataset looks like:

'data.frame':	181 obs. of  344 variables:
 $ Strata: int  51 51 51 51 51 51 51 51 51 51 ...
 $ 1     : int  2 1 1 1 NA 1 1 2 1 1 ...
 $ 2     : int  1 2 1 1 NA 1 1 1 1 1 ...
 $ 3     : int  2 2 2 2 NA 2 2 2 2 2 ...
 $ 4     : int  1 2 1 1 NA 1 1 1 1 1 ...
 $ 5     : int  2 2 NA 2 2 1 1 2 1 2 ...
 $ 6     : int  1 1 NA 1 2 1 1 2 2 2 ...
 $ 7     : int  1 1 1 1 NA 1 2 1 1 1 ...
 $ 8     : int  1 1 1 1 NA 1 2 1 1 1 ...
 $ 9     : int  2 2 2 2 NA 2 2 2 2 2 ...
 $ 10    : int  2 1 2 2 NA 2 2 2 2 2 ...
 $ 11    : int  2 1 2 2 NA 2 2 2 2 2 ...
 $ 12    : int  2 1 2 2 NA 2 2 2 2 2 ...
 $ 13    : int  1 1 1 1 NA 2 2 1 2 1 ...

What am I doing wrong to not be able to get boot.ppfst to work?

**Comment by jgx65** [comment]
Thanks @Erikacj . Could you provide an example data set reproducing the error? I am suspicious that you are using dosage data with a function that works with fstat format data. You could also check the closed issues about `boot.ppfst`.

**Comment by Erikacj** [comment]
Yes, @jgx65, you're correct. I was using dosage data - SNPs. What is the best way to find the population pairwise significance using dosage data? The boot.ppbetas function?

**Comment by jgx65** [comment]
If you can assume your markers are independent,  you could convert the dosage format to fstat format (by replacing 0 with 11, 1 with 12 and 2 with 22) and use `boot.ppfst`  on this new dataset.  If you can't assume independence, `hierfstat` does not have yet a specific function to carry out the test. I suggest you chop the genomes in blocks you assume are independent, calculate Fst for each of these blocks, and bootstrap them, as we do in [Goudet & Weir 2023, Fig S4](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1010871).

**Comment by Erikacj** [comment]
Hi Jerome. Thanks for the help. I was importing the vcf incorrectly before.
It was reducing the data and made it look like dosage data. Now that I have
multilocus genotypes coded correctly I can retrieve population pairwise Fst
using pairwise.WCfst and test for population pairwise significance
using boot.ppbetas. I just want to double check that I understand
correctly, for some populations the output of boot.ppbetas is all negatives
above and below diagonal, does this mean that these comparisons are
insignificant?

**Comment by jgx65** [comment]
If you are willing to assume random mating within populations and the loci are independent.  You can also check if the results are consistent with `hierfstat::boot.ppfst`  (where random mating within populations is not assumed)

**Comment by Erikacj** [comment]
Gotcha. Thank you!
